version: "3.9"
services:
  uro:
    extends:
      file: docker-compose.yml
      service: uro
    build:
      args:
        MIX_ENV: dev
    volumes:
      - ./lib:/app/lib
      - ./config:/app/config
      - ./priv:/app/priv
    links:
      - database
      - redis
    depends_on:
      database:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true

  nextjs:
    extends:
      file: docker-compose.yml
      service: nextjs
    build:
      args:
        NODE_ENV: development
    user: "root"
    depends_on:
      - uro

  database:
    extends:
      file: docker-compose.yml
      service: database

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  caddy:
    extends:
      file: docker-compose.yml
      service: caddy
    volumes:
      - ./Caddyfile.development:/etc/caddy/Caddyfile
    depends_on:
      - uro
      - nextjs

networks:
  uro:
    name: "uro"
    
volumes:
  caddy_data:
  caddy_config:
